### ISSUE TITLE
Rate exceeded

### ISSUE THREAD

**Issue by Darrenh159** [br-g/openf1#113]
Hi, Firstly, thanks for the great API, I've been using it most of this season and its been great.

But recently I am getting 'rate exceeded' after some requests.  Here is what my code is sending for example.

https://api.openf1.org/v1/position?session_key=latest&driver_number=44

Is this something I am doing or can do better to negate this error? Or is it just a case of more people hammering the API?

Thanks,
Darren.

**Comment by adamlefeuvre** [comment]
I've had the same - was fine for a while but the last few races I get rate exceeded, even at the start of the race. If there's an option to support the project, then do let me know - I've already made a donation when I started using it, but happy to support more to have a consistent reliable source of data - the API is great - thank you!

**Comment by andytratter** [comment]
For what it's worth, I noticed the same this weekend. Had a very slow response time during Sprint Quali and then got biffed out due to "Rate Exceeded". At most I would have made 3 requests in under a second. Made 1 request before the Sprint Race and was fine. Made 1 request during the race and got "Rate Exceeded" error again.

**Comment by br-g** [comment]
Hi there!

I am currently limiting requests to 30 every 10 seconds. My infrastructure is under high pressure during sessions, but I’m actively working on improvements to handle the demand more effectively. Thanks for your patience, and apologies for any inconvenience!

**Comment by adamlefeuvre** [comment]
Thanks for the update!  Just to say, all worked a treat during the Mexico GP - thank you :)
