### ISSUE TITLE
Missing Driver Data

### ISSUE THREAD

**Issue by JakobLybarger** [br-g/openf1#128]
Pieces of Driver data are missing for Franco Colapinto and Liam Lawson for the latest event and session. This doesn't seem to a be a problem when I run the ingestor and API locally.

I assume maybe data for the drivers needs to be added to the tmp_fixes.py file.

**Comment by Muzer** [comment]
Yeah, seeing the following for Colapinto:

```
$ wget -qO - "https://api.openf1.org/v1/drivers?session_key=latest&driver_number=43" | jq .
[
  {
    "session_key": 9646,
    "meeting_key": 1251,
    "broadcast_name": "F COLAPINTO",
    "country_code": null,
    "first_name": null,
    "full_name": "Franco COLAPINTO",
    "headshot_url": null,
    "last_name": null,
    "driver_number": 43,
    "team_colour": null,
    "team_name": null,
    "name_acronym": "COL"
  }
]
```

**Comment by br-g** [comment]
Hello!
The new OpenF1 version (v1.0) is not yet running in production. That's why this issue is not reproducible locally.
The new codebase still need a bit of testing, but should be ready soon hopefully :)
