### ISSUE TITLE
Live Data Ingestion

### ISSUE THREAD

**Issue by jocapello** [br-g/openf1#132]
What is the purpose of "The recording must be started at least 1h before the start of the session for races, and at least 15 minutes before the start of the session for practice and qualifying." Does the api really not track any data if this is not followed?

**Comment by brgodefroy** [comment]
In my experience, the session information (with session key, session name, location, etc) is received before the start of the session.
That's why recording needs to start early, at least with the current implementation.

**Comment by br-g** [comment]
In my experience, the session information (with session key, session name, location, etc) is received before the start of the session.
That's why recording needs to start early, at least with the current implementation.
