### ISSUE TITLE
country_name problem

### ISSUE THREAD

**Issue by ohij** [br-g/openf1#135]
How to know the country name to write in the api url
for example the link below for United-Kingdom is not working 
https://api.openf1.org/v1/sessions?country_name=United-Kingdom&session_name=Race&year=2024

Thank you for your help

**Comment by philip-denys** [comment]
'Great Britain'

Here is how I look it up :p
https://api.openf1.org/v1/sessions?session_name=Race&year=2024

**Comment by ohij** [comment]
@philip-denys  Thank you, it was what I was looking for.
I made it work by adding %20 between Great and Britain : ``Great%20Britain``
https://api.openf1.org/v1/sessions?country_name=Great%20Britain&session_name=Race&year=2024
