### ISSUE TITLE
2024 Meetings are Missing (although I appreciate the 2023 races!)

### ISSUE THREAD

**Issue by hwpaige** [br-g/openf1#18]

**Comment by br-g** [comment]
Hello,
For now, only past events are provided by the API.
Future events will be added soon!

**Comment by hwpaige** [comment]
Thanks Bruno!

Sorry about all of the calls I’ve been making this morning while updating my app to handle the 2024 practice I see you added!

I owe you a coffee…or 6.

Maybe when I’m in Paris this May.

Thanks,
Harrison

**Comment by br-g** [comment]
Hello,

 

No worries for your API calls!

The project is still very early and I'm happy to see the first users using it.

 

I would be happy to chat with you when you come to Paris!

 

Best,

Bruno

 


Sent: Thursday, February 29, 2024 at 3:39 PM

**Comment by timespaced** [comment]
> Hello, For now, only past events are provided by the API. Future events will be added soon!

Any ETA on future events?  I would like to code a Widgy widget (iOS) for personal use that will show me the date and times of the next practice/qual/sprint/race :)
