### ISSUE TITLE
Node.js / NPM Package

### ISSUE THREAD

**Issue by Setloth** [br-g/openf1#48]
Is there ever a plan to format this as an https://npmjs.org package for use in Node.js without having to fetch URLs manually?

**Comment by JoostKersjes** [comment]
I think this belongs in the [GitHub Discussions](https://github.com/br-g/openf1/discussions) like mentioned in the [Roadmap section](https://openf1.org/#roadmap).

You could always make it yourself! Here is a good example of an API wrapper library for Node.js that I'm aware of: https://github.com/PokeAPI/pokedex-promise-v2
