### ISSUE TITLE
Shanghai race showing up twice from Meetings API

### ISSUE THREAD

**Issue by KevinCamacho** [br-g/openf1#58]
Not sure if it is a bug related to in-progress race weekends, but this URL
https://api.openf1.org/v1/meetings?year=2024

To get all meetings this year, is returning Shanghai twice (with the same meeting_key).

<img width="1432" alt="image" src="https://github.com/br-g/openf1/assets/10111590/0b90f8d9-445b-412b-8fcd-6e34f791e488">

**Comment by KevinCamacho** [comment]
Update, it appears it is not related to a weekend in progress. The meetings API is still returning Shanghai 2x.

**Comment by br-g** [comment]
Thanks for reporting this issue.
It is fixed now!
