### ISSUE TITLE
Request: CircuitInfo data

### ISSUE THREAD

**Issue by glensargent** [br-g/openf1#7]
I'd love to make use of your API, I'm particularly interested in driver positioning and such but their coords aren't particularly useful without the CircuitInfo present, since the driver coordinates are relative to the CircuitInfo data. Would it be possible to integrate the FastF1 CircuitInfo data in to your API? 

https://docs.fastf1.dev/circuit_info.html#fastf1.mvapi.CircuitInfo

Cheers

**Comment by br-g** [comment]
Hello,

That's sounds like a great idea!
I will try to implement a new endpoint for track info early this year
