### ISSUE TITLE
Get session data for sprint qualifying

### ISSUE THREAD

**Issue by despolov** [br-g/openf1#83]
Hello, 

Im trying to get the session data for a sprint qualifying, but Im unable to do it. I have tried

- https://api.openf1.org/v1/sessions?country_name=Austria&session_name=Sprint_Qualifying&year=2024
- https://api.openf1.org/v1/sessions?country_name=Austria&session_name=SprintQualifying&year=2024
- https://api.openf1.org/v1/sessions?country_name=Austria&session_name=Sprint&year=2024&session_type=Qualifying

but I recieve an empty array. 
How am I supposed to do this api call?

Thanks!

**Comment by rich-howell** [comment]
> Hello,
> 
> Im trying to get the session data for a sprint qualifying, but Im unable to do it. I have tried
> 
> * https://api.openf1.org/v1/sessions?country_name=Austria&session_name=Sprint_Qualifying&year=2024
> * https://api.openf1.org/v1/sessions?country_name=Austria&session_name=SprintQualifying&year=2024
> * https://api.openf1.org/v1/sessions?country_name=Austria&session_name=Sprint&year=2024&session_type=Qualifying
> 
> but I recieve an empty array. How am I supposed to do this api call?
> 
> Thanks!

@despolov  You can do it like this `https://api.openf1.org/v1/sessions?country_name=Austria&session_name=Sprint%20Qualifying&year=2024`

**Comment by despolov** [comment]
Thanks a lot!
